### ISSUE TITLE
Validation with Eclipse

### ISSUE THREAD

**Issue by F43nd1r** [mcasimir/generator-mobileangularui#20]
I've set up a phonegap application with this tool, and it's working fine, with one problem:
Eclipse validation does not work at all. I had to disable all validators to make the build work in eclipse, and it still underlines every css class in the html because it can't be found. Is there any way to resolve this or can you recommend me a better working IDE?

**Comment by mcasimir** [comment]
Hi @F43nd1r, I'm sorry i can't get.. what validators are you referring? 

I don't use Eclipse since my graduation and it was for a Java project. 

Although probably this is not the best place to find help about Eclipse,  from what u're saying it sounds like Eclipse tries to look for css sources where they aren't (they are in a folder under `bower_components` and are `.less` sources).

In that case probably there may be some kind of setting to control that behaviour in Eclipse, but really i don't know how to help.

**Comment by F43nd1r** [comment]
I switched to IntelliJ, where the Phonegap plugin takes care of this. I guess Eclipse is just not the best environment to develop such an application...
